set.seed(42);

             "braycurtis"                                
               "canberra"                                
              "chebyshev"
             "covariance"
              "euclidean"                                
               "equality"                                
              "hellinger"                                
                "jaccard"                                
            "mahalanobis"
              "manhattan"
              "minkowski"
                "pearson"
             "procrustes" 
